name: DockerActionTest

on: [push]

jobs:
  hello_Morisawa:
    runs-on: ubuntu-latest
    name: Hello action
    steps:
      # プライベートアクションを使用するために
      # リポジトリをチェックアウトする
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./.github/actions/action-test
        id: hello
        with:
          who-to-greet: 'Morisawa'
      # 「hello」ステップの出力を使用する
      - name: Get the output time
        run: echo "${{ steps.hello.outputs.time }}"

